// src/constants/errorStatuses.ts
export enum ErrorCodes {
  //INTERNAL CODES -> These should not be exposed to the client, so filter them in error-middleware
  // Database Errors
  DB_COULD_NOT_CONNECT = 'DB_COULD_NOT_CONNECT',
  DB_TIMEOUT = 'DB_TIMEOUT',
  DB_QUERY_FAILED = 'DB_QUERY_FAILED',
  DB_RECORD_NOT_FOUND = 'DB_RECORD_NOT_FOUND',
  DB_CONSTRAINT_VIOLATION = 'DB_CONSTRAINT_VIOLATION',

  // Redis & BullMQ Errors
  REDIS_COULD_NOT_CONNECT = 'REDIS_COULD_NOT_CONNECT',
  NO_QUEUE_FOUND = 'NO_QUEUE_FOUND',
  REDIS_TIMEOUT = 'REDIS_TIMEOUT',
  QUEUE_PROCESSING_FAILED = 'QUEUE_PROCESSING_FAILED',

  // External API & Network Errors
  THIRD_PARTY_SERVICE_ERROR = 'THIRD_PARTY_SERVICE_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
  TIMEOUT_ERROR = 'TIMEOUT_ERROR',

  //CLIENT SAFE CODES

  // Authentication & Authorization Errors
  UNAUTHORIZED = 'UNAUTHORIZED',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  ACCESS_DENIED = 'ACCESS_DENIED',

  // Validation Errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Request & API Errors
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  PAYMENT_REQUIRED = 'PAYMENT_REQUIRED',
}

// Get an array of values if needed
