#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm run format  # Ensures Prettier formatting is correct
pnpm exec lint-staged  # Runs lint-staged on staged files
pnpm npx cucumber-js  # Runs tests before committing
